stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f docker/Dockerfile .
    - docker push $IMAGE_TAG

update_manifest:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git yq
  script:
    # Patch manifest with new image tag
    - yq e -i ".spec.template.spec.containers[0].image = \"$IMAGE_TAG\"" manifests/deployment.yaml
    - git config user.name "GitLab CI"
    - git config user.email "ci@example.com"
    - git add manifests/deployment.yaml
    - git commit -m "Update image to $IMAGE_TAG"
    - git push origin HEAD:$CI_COMMIT_REF_NAME
