apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30090 # Adjust as needed
  type: NodePort
  template:
    spec:
      containers:
        - image: ghcr.io/staocube88/nodewithdb:b7ffc3f
