apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  template:
    spec:
      containers:
        - image: ghcr.io/staocube88/nodewithdb:b7ffc3f
