apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
<<<<<<< HEAD
          image: mongo:6
=======
          image: ghcr.io/staocube88/nodewithdb:e5e89c4
>>>>>>> 21f25473984bb3082f388f01ff9a0cc129ec480d
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: mongo-data
          emptyDir: {}
