name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase image name and IMAGE_TAG
      id: vars
      run: |
        IMAGE_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG=${{ env.REGISTRY }}/${IMAGE_NAME}:${GITHUB_SHA::7}
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_TAG -f Dockerfile .
        docker push $IMAGE_TAG

    - name: Update K8s manifests with new image
      run: |
        for file in k8s/*.yml; do
          yq -i '.spec.template.spec.containers[0].image = env(IMAGE_TAG)' "$file"
        done

    - name: Commit and push updated manifest
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add k8s/
        git commit -m "Update image to $IMAGE_TAG" || echo "No changes to commit"
        git push
